# Generated by Django 4.2.1 on 2023-06-03 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 8, 12, 3, 676524, tzinfo=datetime.timezone.utc)),
        ),
    ]
